/**
 * Midjourney V7 model schemas (image + video)
 */

import { ModelInfo } from '../../types/models';

export const MIDJOURNEY_V7_MODELS: Record<string, ModelInfo> = {
  'midjourney-v7': {
    name: 'Midjourney V7 (Latest)',
    description: 'Latest Midjourney model with Standard and Draft modes',
    version: '7',
    provider: 'midjourney',
    limits: {
      context_tokens: 4096,
      output_tokens: 0,
      rate_limit: 'Depends on relay configuration',
    },
    inputs: [
      {
        name: 'prompt',
        type: 'string',
        required: true,
        description: 'Primary prompt with scene description and stylistic hints',
      },
      {
        name: 'mode',
        type: 'string',
        required: false,
        description: 'Generation mode',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard' },
          { value: 'raw', label: 'Raw' },
        ],
      },
      {
        name: 'aspect_ratio',
        type: 'string',
        required: false,
        description: 'Image aspect ratio',
        default: 'square',
        options: [
          { value: 'portrait', label: 'Portrait (2:3)' },
          { value: 'square', label: 'Square (1:1)' },
          { value: 'landscape', label: 'Landscape (3:2)' },
        ],
      },
      {
        name: 'stylization',
        type: 'number',
        required: false,
        description: 'How much Midjourney\'s aesthetic style affects the image (0-1000)',
        default: 100,
        min: 0,
        max: 1000,
      },
      {
        name: 'weirdness',
        type: 'number',
        required: false,
        description: 'Explore unusual aesthetics (0-3000)',
        default: 0,
        min: 0,
        max: 3000,
      },
      {
        name: 'variety',
        type: 'number',
        required: false,
        description: 'Variation between image outputs (0-100)',
        default: 0,
        min: 0,
        max: 100,
      },
      {
        name: 'speed',
        type: 'string',
        required: false,
        description: 'Generation speed',
        default: 'fast',
        options: [
          { value: 'relax', label: 'Relax' },
          { value: 'fast', label: 'Fast' },
          { value: 'turbo', label: 'Turbo' },
        ],
      },
      {
        name: 'image_prompt',
        type: 'image',
        required: false,
        description: 'Image Prompts - Visual references to guide composition and palette',
      },
      {
        name: 'style_reference',
        type: 'image',
        required: false,
        description: 'Style References - Use the aesthetic of an image to guide generation',
      },
      {
        name: 'omni',
        type: 'image',
        required: false,
        description: 'Omni Reference - Ensure consistent character likeness across generations (replaces --cref in V7)',
      },
    ],
    file_format: 'url',
    documentation_url: 'https://docs.midjourney.com/docs/quick-start',
  },

  'midjourney-v7-video': {
    name: 'Midjourney V7 Video',
    description: 'Midjourney V7 optimized for video generation',
    version: '7',
    provider: 'midjourney',
    limits: {
      context_tokens: 8192,
      output_tokens: 0,
      rate_limit: 'Depends on relay configuration',
    },
    inputs: [
      {
        name: 'prompt',
        type: 'string',
        required: true,
        description: 'Narrative prompt describing the motion and key beats',
      },
      {
        name: 'mode',
        type: 'string',
        required: false,
        description: 'Generation mode',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard' },
          { value: 'raw', label: 'Raw' },
        ],
      },
      {
        name: 'stylization',
        type: 'number',
        required: false,
        description: 'How much Midjourney\'s aesthetic style affects the video (0-1000)',
        default: 100,
        min: 0,
        max: 1000,
      },
      {
        name: 'weirdness',
        type: 'number',
        required: false,
        description: 'Explore unusual aesthetics (0-3000)',
        default: 0,
        min: 0,
        max: 3000,
      },
      {
        name: 'variety',
        type: 'number',
        required: false,
        description: 'Variation between video outputs (0-100)',
        default: 0,
        min: 0,
        max: 100,
      },
      {
        name: 'speed',
        type: 'string',
        required: false,
        description: 'Generation speed',
        default: 'fast',
        options: [
          { value: 'relax', label: 'Relax' },
          { value: 'fast', label: 'Fast' },
          { value: 'turbo', label: 'Turbo' },
        ],
      },
      {
        name: 'video_resolution',
        type: 'string',
        required: false,
        description: 'Video quality',
        default: 'hd',
        options: [
          { value: 'sd', label: 'SD' },
          { value: 'hd', label: 'HD' },
        ],
      },
      {
        name: 'video_batch_size',
        type: 'string',
        required: false,
        description: 'Number of videos to generate',
        default: '4',
        options: [
          { value: '1', label: '1' },
          { value: '2', label: '2' },
          { value: '4', label: '4' },
        ],
      },
      {
        name: 'first_frame_image',
        type: 'image',
        required: false,
        description: 'Optional first frame reference to anchor the opening scene',
      },
      {
        name: 'end_frame_image',
        type: 'image',
        required: false,
        description: 'Optional final frame reference for the closing shot',
      },
      {
        name: 'timeline_prompt',
        type: 'string',
        required: false,
        description: 'Storyboard-style prompt describing transitions and pacing',
      },
      {
        name: 'duration_seconds',
        type: 'number',
        required: false,
        description: 'Requested video duration in seconds',
      },
      {
        name: 'audio_track_url',
        type: 'audio',
        required: false,
        description: 'Optional soundtrack URL synchronized with the render',
      },
    ],
    file_format: 'url',
    documentation_url: 'https://docs.midjourney.com/docs/video-mode',
  },
};
